name: Run Gradle check

on:
  push:
    branches:
      - main
      - releases/*
  pull_request:

jobs:
  gradle-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
    - name: setup gradle
      uses: gradle/gradle-build-action@v2.1.0
    - name: gradle check
      run: ./gradlew check
    - name: publish coveralls
      run: ./gradlew coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
